### ISSUE TITLE
Code coverage failing after repo transfer

### ISSUE THREAD

**Issue by Grinkers** [edn-rs/edn-rs#128]
Maybe we should just remove it? I don't think `tarpaulin` is particularly accurate anyway.

https://blog.rng0.io/how-to-do-code-coverage-in-rust/
Source-based code coverage seems to be the new hotness, but I think it has problems with merging features? I want to take a serious attempt at no_std. So I think all the coverage tooling will probably be a bit iffy. It already is with feature gating and macros.

I'm not really finding any good examples of any open source projects using any coverage tools with CI. I think maybe nothing is better than inaccurate/misleading.

**Comment by Grinkers** [comment]
Also, while doing cleanup or maintenance, maybe we rename the default branch to `main`?

**Comment by Grinkers** [comment]
Oh, sorry. It looks like it was a thing from me working on a fork. The other things mentioned are still valid, but this isn't a real issue.

**Comment by naomijub** [comment]
I can rename the branch to main in another issue

**Comment by naomijub** [comment]
> Also, while doing cleanup or maintenance, maybe we rename the default branch to `main`?

Done @Grinkers @evaporei
