### ISSUE TITLE
crates.io publishing

### ISSUE THREAD

**Issue by Grinkers** [edn-rs/edn-rs#138]
@naomijub 

https://github.com/edn-rs/edn-derive/issues/34
following up on this.

I've linked my github to crates.io

```
Name
    Kevin Nakamura
GitHub Account
    Grinkers
 Email
    grinkers@grinkers.net Verified! 
 ```
 
 However I think it'd be best to link github itself with an action to publish based on releases? Not individuals.

**Comment by naomijub** [comment]
good call, I have granted access to crates.io

**Comment by Grinkers** [comment]
> good call, I have granted access to crates.io

I think you'll need to add a token to the repo in the secrets? I've never published to crates.io, so I don't know how it all works.

**Comment by naomijub** [comment]
CRATES_TOKEN should solve in both crates

**Comment by Grinkers** [comment]
https://github.com/edn-rs/edn-rs/issues/158
No need if there's not many releases.
