### ISSUE TITLE
PRs blocked by CI not returning status

### ISSUE THREAD

**Issue by Grinkers** [edn-rs/edn-rs#145]
```
build Expected — Waiting for status to be reported
cargo test Expected — Waiting for status to be reported
```

https://github.com/edn-rs/edn-rs/pull/143
As seen here.

https://github.com/edn-rs/edn-rs/actions/runs/7403645375
All 28 of Github's CI is succeeding.

@naomijub I think you'll have to investigate this. I'm not even sure where these are coming from and can't see the settings.

**Comment by Grinkers** [comment]
@naomijub 
bump. It would be nice to get all changes merged upstream.

**Comment by naomijub** [comment]
> @naomijub bump. It would be nice to get all changes merged upstream.

CI name changes caused it, lets keep Actions with the same names

**Comment by Grinkers** [comment]
Looks like you solved it. Closing.
