### ISSUE TITLE
Improper Handling of `Inst`

### ISSUE THREAD

**Issue by bowbahdoe** [edn-rs/edn-rs#83]
Inst is usually represented in EDN as a tagged type `#inst`

**Comment by naomijub** [comment]
[Edn spec](https://github.com/edn-format/edn#inst-rfc-3339-format) and the result with edn-rs `Map(Map({":date": Inst("1985-04-12T23:20:50.52Z")}))` for parsing `{:date #inst "1985-04-12T23:20:50.52Z"}`

**Comment by bowbahdoe** [comment]
and if you write the inst out again, you get `"1985-04-12T23:20:50.52Z"`, not `#inst "1985-04-12T23:20:50.52Z"`
