### ISSUE TITLE
Handling numbers with an exponent

### ISSUE THREAD

**Issue by kyptin** [edn-rs/edn-rs#96]
Thanks for the library.

I was using it today and discovered that numbers with an exponent, like this:

    5.01122771367421E15

…are valid according to [the spec](https://github.com/edn-format/edn#floating-point-numbers) but aren't handled correctly by this library.

Thought y'all might like to know. Cheers.

**Comment by naomijub** [comment]
Thanks, I will take a look, that should be fairly simple to fix

**Comment by naomijub** [comment]
Really nice catch, also there was a problem with floats that are less than 0.0. Now they are fixed https://github.com/naomijub/edn-rs/pull/97.

Version `0.17.3`
